### ISSUE TITLE
To strict a spec for URLs?

### ISSUE THREAD

**Issue by dharrigan** [RokLenarcic/clj-rest-client#2]
Hi,

Just trying out your library and I'm coming up against something.

Normally, I define URLs and paths as variables in a configuration file, i.e., config.edn

```
{:base-url "http://foo/bar"
 :person-query "/person/{id}"}
```

I then pull that config into my app. This allows the urls to be changed for different environments (esp the base-url). Unfortunately, trying to use variables with clj-rest-client throws up a spec error, e.g.,

```
(def base-url (:base-url env))
(def person-query (:person-query env))

(defrest {base-url {person-query {GET person-lookup []}}})
```

throws this (only showing the base-url one, person-query is the same):

```
...
:path [:def :subpath :path-part :simple-path],
:pred clojure.core/string?,
:val (var base-url),
...
```

Have I interpreted this incorrectly? 

Thank you.

-=david=-

**Comment by RokLenarcic** [comment]
The issue is that using macro directly with a map literal, the macro gets unevaluated map literal. So for the macro your variables are just symbols, `person-query` and `GET` are both symbols and spec for the macro takes any symbols in the map literal passed in as HTTP METHOD. You also have another error `{GET person-lookup []}` should be `{GET (person-lookup [])}`

One way around that is to declare map into a variable, and pass variable to the macro:

```
(def base-url (:base-url env))
(def person-query (:person-query env))
; see tutorials for keyword based definition
(def api {base-url {person-query '{GET (person-lookup [])}}}

(defrest api)
```

Generally I avoid that altogether, because different environments use different base urls, but API subpaths tend to be the same even in different environments. And base URL (and config) is generally not known at macro expansion time.  So I use client objects as described in tutorial, here's an example:

```
(defn client [url user pass]
  (fn [req]
    (-> req
        (assoc :basic-auth [user pass])
        (update :url #(str url "/" %))
        client/request)))
```

Then I do:

```
(def cli (client (:base-url env) (:user env) (:password env)))

(cli (person-lookup))
```

That's my preferred approach.

**Comment by dharrigan** [comment]
Hi!

I see, okay, thank you. That makes perfect sense. I'll close the issue. 

I'm eager to experiment more with this API and learn more about it :-)

Thank you for replying :-)

-=david=-
